[package]
name = "example-block-traces"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unreachable_pub = "warn"
unused_must_use = "deny"
rust_2018_idioms = "deny"

[lints.rustdoc]
all = "warn"

[dependencies]
# revm
revm = { workspace = true, features = ["std", "alloydb", "serde-json"] }
mantle-revm = { path = "../../crates/mantle/" }

# tokio
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

# alloy
alloy-eips.workspace = true
alloy-provider = { workspace = true, default-features = true }
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine = "0.14.0"
alloy-rpc-types-eth = "0.14.0"

op-alloy-consensus = { git = "https://github.com/mantle-xyz/op-alloy", branch = "v141", default-features = false, features = [
    "k256",
] }
op-alloy-network = { git = "https://github.com/mantle-xyz/op-alloy", branch = "v141", default-features = false }
op-alloy-rpc-types-engine = { git = "https://github.com/mantle-xyz/op-alloy", branch = "v141", default-features = false,features = [
    "k256"
] }

# progress bar
indicatif.workspace = true

# misc
anyhow.workspace = true
